version: "3.9"
services:

  web:
    build: .
    container_name: user-interface
    ports:
      - "5000:5000"
    volumes:
      - .:/data
    environment:
      FLASK_ENV: development
  
  rstudio:
    image: "rocker/rstudio"
    container_name: rstudio
    ports:
      - "8787:8787"
    environment:
      - DISABLE_AUTH=true

  hadoop:
    image: "harisekhon/hadoop"
    container_name: hadoop
    stdin_open: true
    ports:
      - "8020:8020"
      - "8042:8042"
      - "8088:8088"
      - "9868:9868"
      - "9870:9870"
      - "10020:10020"
      - "19888:19888"

  spyder:
    image: "compdatasci/spyder-desktop"
    container_name: spyder
    ports:
     - "6080:6080"
    environment:
      - PASSWORD=spyder
      
  vs-code:
    image: "codercom/code-server"
    container_name: vs-code
    ports:
        - "8080:8080"
    environment:
      - PASSWORD=vscode
      
  spark:
    image: "bitnami/spark"
    container_name: spark
    stdin_open: true
    ports:
      - "8081:8081"
    environment: 
      - SPARK_MODE=master
      
  #ibm-sas:
    # using website

  #tableau:
    # using website

  git:
    image: "madisonhaugh/git:git"
    container_name: git
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - .:/data
   
  sonar-qube:
    image: "sonarqube"
    container_name: sonar-qube
    stdin_open: true
    ports:
      - "9000:9001"
#    networks:
#      - sonarnetwork

  sonar-scanner:
    image: "newtmitch/sonar-scanner"
    stdin_open: true
#    networks:
#      - sonarnetwork

#  networks:
#    sonarnetwork:

  jupyter:
    image: "jupyter/base-notebook"
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/data
    environment:
      - JUPYTER_TOKEN=jupyter
      
  tensorflow:
    image: "tensorflow/tensorflow"
    container_name: tensorflow
    ports:
      - "8889:8889"
    environment:
      - JUPYTER_TOKEN=tensorflow
      
  orange:
    image: "acopar/orange-docker"
    container_name: orange
    ports:
      - "5901:5901"
      - "6901:6901"
    environment:
      - PASSWORD=orange
      
  markdown:
    image: "v4tech/markdown-editor"
    container_name: markdown
    ports:
      - "12345:80"